[package]
name = "grafana-resource"
version = "0.1.0"
authors = ["Mohamad al moualem <m.almouallem@gmail.com>"]

[dependencies]
rustana = { path = "../rustana" }
serde_json = "1.0.39"
serde = { version = "1.0.91", features = ["derive"] }